# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mohao.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Micrometer(object):
    def setupUi(self, Micrometer):
        Micrometer.setObjectName("Micrometer")
        Micrometer.resize(795, 569)
        self.pushButton = QtWidgets.QPushButton(Micrometer)
        self.pushButton.setGeometry(QtCore.QRect(160, 20, 61, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Micrometer)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 20, 101, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit_2 = QtWidgets.QTextEdit(Micrometer)
        self.textEdit_2.setGeometry(QtCore.QRect(180, 60, 531, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_4 = QtWidgets.QTextEdit(Micrometer)
        self.textEdit_4.setGeometry(QtCore.QRect(180, 100, 531, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(Micrometer)
        self.textEdit_5.setGeometry(QtCore.QRect(70, 200, 641, 321))
        self.textEdit_5.setObjectName("textEdit_5")
        self.pushButton_3 = QtWidgets.QPushButton(Micrometer)
        self.pushButton_3.setGeometry(QtCore.QRect(610, 530, 101, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Micrometer)
        self.pushButton_4.setGeometry(QtCore.QRect(360, 20, 101, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(Micrometer)
        self.label.setGeometry(QtCore.QRect(70, 540, 161, 16))
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(Micrometer)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 20, 91, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(Micrometer)
        self.label_2.setGeometry(QtCore.QRect(70, 70, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Micrometer)
        self.label_3.setGeometry(QtCore.QRect(70, 110, 141, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Micrometer)
        self.lineEdit.setGeometry(QtCore.QRect(70, 140, 641, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_6 = QtWidgets.QPushButton(Micrometer)
        self.pushButton_6.setGeometry(QtCore.QRect(480, 20, 111, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_4 = QtWidgets.QLabel(Micrometer)
        self.label_4.setGeometry(QtCore.QRect(70, 180, 141, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_7 = QtWidgets.QPushButton(Micrometer)
        self.pushButton_7.setGeometry(QtCore.QRect(600, 20, 111, 28))
        self.pushButton_7.setObjectName("pushButton_7")

        self.retranslateUi(Micrometer)
        self.pushButton.clicked.connect(Micrometer.start)
        self.pushButton_2.clicked.connect(Micrometer.delete)
        self.pushButton_3.clicked.connect(Micrometer.end)
        self.pushButton_4.clicked.connect(Micrometer.next)
        self.pushButton_6.clicked.connect(Micrometer.new)
        self.pushButton_7.clicked.connect(Micrometer.info)
        QtCore.QMetaObject.connectSlotsByName(Micrometer)

    def retranslateUi(self, Micrometer):
        _translate = QtCore.QCoreApplication.translate
        Micrometer.setWindowTitle(_translate("Micrometer", "Micrometer"))
        self.pushButton.setText(_translate("Micrometer", "测量"))
        self.pushButton_2.setText(_translate("Micrometer", "删除当前测点"))
        self.textEdit_4.setHtml(_translate("Micrometer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_5.setHtml(_translate("Micrometer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_3.setText(_translate("Micrometer", "保存并退出"))
        self.pushButton_4.setText(_translate("Micrometer", "开始下一组"))
        self.label.setText(_translate("Micrometer", "@梁型"))
        self.pushButton_5.setText(_translate("Micrometer", "请输入站点"))
        self.label_2.setText(_translate("Micrometer", "垂磨量（mm）："))
        self.label_3.setText(_translate("Micrometer", "侧磨量（mm）："))
        self.pushButton_6.setText(_translate("Micrometer", "开始新的区段"))
        self.label_4.setText(_translate("Micrometer", "信息栏："))
        self.pushButton_7.setText(_translate("Micrometer", "使用说明"))
